In [1]:
import torch

In [34]:
# Создайте случайный FloatTensor размера 3x4x5
x = torch.rand(3, 4, 5, dtype=torch.float) 
x

tensor([[[0.9549, 0.8938, 0.5840, 0.7678, 0.3593],
         [0.9655, 0.7123, 0.0836, 0.1693, 0.6652],
         [0.3330, 0.3163, 0.0122, 0.5328, 0.9736],
         [0.0581, 0.6228, 0.1091, 0.7425, 0.5461]],

        [[0.2329, 0.8115, 0.3756, 0.8587, 0.7729],
         [0.5903, 0.1356, 0.2232, 0.8219, 0.5439],
         [0.0907, 0.7935, 0.9113, 0.8699, 0.1380],
         [0.9320, 0.6955, 0.2343, 0.9488, 0.9204]],

        [[0.2819, 0.0668, 0.0590, 0.9475, 0.0272],
         [0.5054, 0.0165, 0.8700, 0.3811, 0.6853],
         [0.4413, 0.4697, 0.1586, 0.3558, 0.7662],
         [0.7092, 0.5692, 0.1097, 0.3709, 0.1713]]])

In [35]:
# Выведите его форму (shape)
print(x.shape)

torch.Size([3, 4, 5])


In [36]:
# Приведите его к форме 6 X 10
x1 = x.reshape(6, 10)
x1

tensor([[0.9549, 0.8938, 0.5840, 0.7678, 0.3593, 0.9655, 0.7123, 0.0836, 0.1693,
         0.6652],
        [0.3330, 0.3163, 0.0122, 0.5328, 0.9736, 0.0581, 0.6228, 0.1091, 0.7425,
         0.5461],
        [0.2329, 0.8115, 0.3756, 0.8587, 0.7729, 0.5903, 0.1356, 0.2232, 0.8219,
         0.5439],
        [0.0907, 0.7935, 0.9113, 0.8699, 0.1380, 0.9320, 0.6955, 0.2343, 0.9488,
         0.9204],
        [0.2819, 0.0668, 0.0590, 0.9475, 0.0272, 0.5054, 0.0165, 0.8700, 0.3811,
         0.6853],
        [0.4413, 0.4697, 0.1586, 0.3558, 0.7662, 0.7092, 0.5692, 0.1097, 0.3709,
         0.1713]])

In [37]:
# Умножьте его на вектор [1, 4, 2, 2, 1] поэлементно
x2 = x1 * torch.tensor([1, 4, 2, 2, 1])
x2.shape

RuntimeError: The size of tensor a (10) must match the size of tensor b (5) at non-singleton dimension 1

In [42]:
# ^^ такой вариант не сработал, последняя размерность должна совпадать с размером вектора, приведем к подходящей форме и обратно
# Умножьте его на вектор [1, 4, 2, 2, 1] поэлементно
x2 = (x1.reshape(12, 5) * torch.tensor([1, 4, 2, 2, 1])).reshape(6, 10)
print(x2.shape)
x2

torch.Size([6, 10])


tensor([[0.9549, 3.5754, 1.1680, 1.5355, 0.3593, 0.9655, 2.8493, 0.1672, 0.3385,
         0.6652],
        [0.3330, 1.2650, 0.0245, 1.0655, 0.9736, 0.0581, 2.4913, 0.2182, 1.4850,
         0.5461],
        [0.2329, 3.2461, 0.7512, 1.7174, 0.7729, 0.5903, 0.5425, 0.4463, 1.6438,
         0.5439],
        [0.0907, 3.1741, 1.8225, 1.7398, 0.1380, 0.9320, 2.7821, 0.4686, 1.8977,
         0.9204],
        [0.2819, 0.2674, 0.1180, 1.8951, 0.0272, 0.5054, 0.0662, 1.7399, 0.7622,
         0.6853],
        [0.4413, 1.8787, 0.3172, 0.7116, 0.7662, 0.7092, 2.2770, 0.2193, 0.7418,
         0.1713]])

In [43]:
# Умножьте тензор матрично на себя, чтобы результат был размерности 6x6
x3 = x2 @ x2.T
print(x3.shape)
x3

torch.Size([6, 6])


tensor([[27.1823, 14.9124, 18.7294, 26.4449,  5.9640, 16.4511],
        [14.9124, 12.5559, 11.0060, 16.4862,  4.5606, 10.9922],
        [18.7294, 11.0060, 18.5426, 20.6769,  7.0342, 11.3182],
        [26.4449, 16.4862, 20.6769, 29.7272,  7.9378, 16.5888],
        [ 5.9640,  4.5606,  7.0342,  7.9378,  8.0947,  3.6071],
        [16.4511, 10.9922, 11.3182, 16.5888,  3.6071, 11.2334]])

In [78]:
# Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)
from torch.autograd import Variable

x = Variable(torch.tensor([1.]), requires_grad = True)
z = Variable(torch.tensor([0.5]), requires_grad = True)
t = Variable(torch.tensor([2.]), requires_grad = True)

y = x**3 + z - 75 * t
print(y)
print(x.grad, z.grad, t.grad)
y.backward()
print(x.grad, z.grad, t.grad)


tensor([-148.5000], grad_fn=<SubBackward0>)
None None None
tensor([3.]) tensor([1.]) tensor([-75.])


In [79]:
# Создайте единичный тензор размера 5x6
x = torch.ones(5, 6)
print(x.shape)
x

torch.Size([5, 6])


tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

In [80]:
# Переведите его в формат numpy
xnp = x.numpy()
print(xnp.shape)
xnp

(5, 6)


array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]], dtype=float32)

In [125]:
# Давайте теперь пооптимизируем: возьмите функцию y = x**w1 - 2 * x**2 + 5
# Посчитайте 
#
# Зададим y и x и подберем w1 по близости функции к целевому y.
from torch import optim
from torch import nn 

x = torch.tensor([2., 2., 3.])
y = x ** 3 - 2 * x ** 2 + 5 # будем искать w1 = 3

print('x = ', x)
print('y = ', y)


w1 = Variable(torch.tensor([1.]), requires_grad = True)

criterion = nn.MSELoss()
optimizer = torch.optim.Adam([w1], lr=0.01)

for i in range(1000):
    print(f'------- итерация {i} ------------------')
    optimizer.zero_grad()

    pred = x ** w1 - 2 * x ** 2 + 5
    print('w1=', w1, ', pred = ', pred)

    loss = criterion(pred, y)
    print('loss = ', loss)
    loss.backward()
    print('dL/dw1 = ', w1.grad)
    optimizer.step()
    if abs(w1.grad) < 0.0001:
        break
        
# найдено значение 3.

x =  tensor([2., 2., 3.])
y =  tensor([ 5.,  5., 14.])
------- итерация 0 ------------------
w1= tensor([1.], requires_grad=True) , pred =  tensor([ -1.,  -1., -10.], grad_fn=<AddBackward0>)
loss =  tensor(216., grad_fn=<MseLossBackward0>)
dL/dw1 =  tensor([-63.8237])
------- итерация 1 ------------------
w1= tensor([1.0100], requires_grad=True) , pred =  tensor([-0.9861, -0.9861, -9.9669], grad_fn=<AddBackward0>)
loss =  tensor(215.3589, grad_fn=<MseLossBackward0>)
dL/dw1 =  tensor([-64.3839])
------- итерация 2 ------------------
w1= tensor([1.0200], requires_grad=True) , pred =  tensor([-0.9721, -0.9721, -9.9333], grad_fn=<AddBackward0>)
loss =  tensor(214.7122, grad_fn=<MseLossBackward0>)
dL/dw1 =  tensor([-64.9482])
------- итерация 3 ------------------
w1= tensor([1.0300], requires_grad=True) , pred =  tensor([-0.9580, -0.9580, -9.8995], grad_fn=<AddBackward0>)
loss =  tensor(214.0595, grad_fn=<MseLossBackward0>)
dL/dw1 =  tensor([-65.5166])
------- итерация 4 ------------------


loss =  tensor(169.3125, grad_fn=<MseLossBackward0>)
dL/dw1 =  tensor([-101.7469])
------- итерация 55 ------------------
w1= tensor([1.5820], requires_grad=True) , pred =  tensor([-6.1884e-03, -6.1884e-03, -7.3141e+00], grad_fn=<AddBackward0>)
loss =  tensor(168.1385, grad_fn=<MseLossBackward0>)
dL/dw1 =  tensor([-102.6117])
------- итерация 56 ------------------
w1= tensor([1.5935], requires_grad=True) , pred =  tensor([ 0.0178,  0.0178, -7.2416], grad_fn=<AddBackward0>)
loss =  tensor(166.9505, grad_fn=<MseLossBackward0>)
dL/dw1 =  tensor([-103.4816])
------- итерация 57 ------------------
w1= tensor([1.6051], requires_grad=True) , pred =  tensor([ 0.0421,  0.0421, -7.1680], grad_fn=<AddBackward0>)
loss =  tensor(165.7483, grad_fn=<MseLossBackward0>)
dL/dw1 =  tensor([-104.3564])
------- итерация 58 ------------------
w1= tensor([1.6167], requires_grad=True) , pred =  tensor([ 0.0667,  0.0667, -7.0931], grad_fn=<AddBackward0>)
loss =  tensor(164.5318, grad_fn=<MseLossBackward0>)
dL/

dL/dw1 =  tensor([-147.0983])
------- итерация 117 ------------------
w1= tensor([2.3577], requires_grad=True) , pred =  tensor([2.1255, 2.1255, 0.3323], grad_fn=<AddBackward0>)
loss =  tensor(67.7771, grad_fn=<MseLossBackward0>)
dL/dw1 =  tensor([-147.0772])
------- итерация 118 ------------------
w1= tensor([2.3707], requires_grad=True) , pred =  tensor([2.1719, 2.1719, 0.5240], grad_fn=<AddBackward0>)
loss =  tensor(65.8667, grad_fn=<MseLossBackward0>)
dL/dw1 =  tensor([-146.9990])
------- итерация 119 ------------------
w1= tensor([2.3837], requires_grad=True) , pred =  tensor([2.2186, 2.2186, 0.7181], grad_fn=<AddBackward0>)
loss =  tensor(63.9603, grad_fn=<MseLossBackward0>)
dL/dw1 =  tensor([-146.8613])
------- итерация 120 ------------------
w1= tensor([2.3966], requires_grad=True) , pred =  tensor([2.2657, 2.2657, 0.9148], grad_fn=<AddBackward0>)
loss =  tensor(62.0590, grad_fn=<MseLossBackward0>)
dL/dw1 =  tensor([-146.6621])
------- итерация 121 ------------------
w1= tensor

loss =  tensor(0.0185, grad_fn=<MseLossBackward0>)
dL/dw1 =  tensor([-4.7810])
------- итерация 186 ------------------
w1= tensor([2.9947], requires_grad=True) , pred =  tensor([ 4.9707,  4.9707, 13.8436], grad_fn=<AddBackward0>)
loss =  tensor(0.0087, grad_fn=<MseLossBackward0>)
dL/dw1 =  tensor([-3.2904])
------- итерация 187 ------------------
w1= tensor([2.9969], requires_grad=True) , pred =  tensor([ 4.9830,  4.9830, 13.9092], grad_fn=<AddBackward0>)
loss =  tensor(0.0029, grad_fn=<MseLossBackward0>)
dL/dw1 =  tensor([-1.9158])
------- итерация 188 ------------------
w1= tensor([2.9990], requires_grad=True) , pred =  tensor([ 4.9942,  4.9942, 13.9690], grad_fn=<AddBackward0>)
loss =  tensor(0.0003, grad_fn=<MseLossBackward0>)
dL/dw1 =  tensor([-0.6551])
------- итерация 189 ------------------
w1= tensor([3.0008], requires_grad=True) , pred =  tensor([ 5.0044,  5.0044, 14.0233], grad_fn=<AddBackward0>)
loss =  tensor(0.0002, grad_fn=<MseLossBackward0>)
dL/dw1 =  tensor([0.4937])
--

loss =  tensor(0.0002, grad_fn=<MseLossBackward0>)
dL/dw1 =  tensor([-0.5454])
------- итерация 255 ------------------
w1= tensor([2.9991], requires_grad=True) , pred =  tensor([ 4.9953,  4.9953, 13.9747], grad_fn=<AddBackward0>)
loss =  tensor(0.0002, grad_fn=<MseLossBackward0>)
dL/dw1 =  tensor([-0.5340])
------- итерация 256 ------------------
w1= tensor([2.9992], requires_grad=True) , pred =  tensor([ 4.9954,  4.9954, 13.9754], grad_fn=<AddBackward0>)
loss =  tensor(0.0002, grad_fn=<MseLossBackward0>)
dL/dw1 =  tensor([-0.5200])
------- итерация 257 ------------------
w1= tensor([2.9992], requires_grad=True) , pred =  tensor([ 4.9955,  4.9955, 13.9762], grad_fn=<AddBackward0>)
loss =  tensor(0.0002, grad_fn=<MseLossBackward0>)
dL/dw1 =  tensor([-0.5038])
------- итерация 258 ------------------
w1= tensor([2.9992], requires_grad=True) , pred =  tensor([ 4.9957,  4.9957, 13.9770], grad_fn=<AddBackward0>)
loss =  tensor(0.0002, grad_fn=<MseLossBackward0>)
dL/dw1 =  tensor([-0.4855])
-

w1= tensor([3.0000], requires_grad=True) , pred =  tensor([ 5.0001,  5.0001, 14.0003], grad_fn=<AddBackward0>)
loss =  tensor(2.8396e-08, grad_fn=<MseLossBackward0>)
dL/dw1 =  tensor([0.0060])
------- итерация 322 ------------------
w1= tensor([3.0000], requires_grad=True) , pred =  tensor([ 5.0000,  5.0000, 14.0002], grad_fn=<AddBackward0>)
loss =  tensor(1.6011e-08, grad_fn=<MseLossBackward0>)
dL/dw1 =  tensor([0.0045])
------- итерация 323 ------------------
w1= tensor([3.0000], requires_grad=True) , pred =  tensor([ 5.0000,  5.0000, 14.0001], grad_fn=<AddBackward0>)
loss =  tensor(7.1159e-09, grad_fn=<MseLossBackward0>)
dL/dw1 =  tensor([0.0030])
------- итерация 324 ------------------
w1= tensor([3.0000], requires_grad=True) , pred =  tensor([ 5.0000,  5.0000, 14.0001], grad_fn=<AddBackward0>)
loss =  tensor(2.1749e-09, grad_fn=<MseLossBackward0>)
dL/dw1 =  tensor([0.0017])
------- итерация 325 ------------------
w1= tensor([3.0000], requires_grad=True) , pred =  tensor([ 5.0000, 